[package]
name = "osmbin_rust"
version = "0.1.0"
edition = "2021"
description = "Library to handle OsmBin format for OpenStreetMap"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
osmpbfreader = "0.16.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
