name: Check and Lint

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends \
            libgeos-dev
      - run: cargo check
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features
      - run: cargo test
