name: Deploy

on:
  push:
    tags:
      # Regex for a version number such as 0.2.1
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends \
            libgeos-dev
      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - run: cargo build --release

      - name: Build archive
        shell: bash
        run: |
          dirname="osm-replication-${{ env.VERSION }}"
          mkdir "$dirname"
          mv "target/release/diffs" "$dirname"
          mv "target/release/osmbin" "$dirname"
          mv "target/release/osmxml" "$dirname"
          mv "target/release/update" "$dirname"
          tar -czf "$dirname.tar.gz" "$dirname"
          echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV

      - name: Upload the binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}
